theme = "catppuccin-mocha"

[editor]
program = "nvim"
args = []

[fonts]
size = 20
family = "Maple Mono NF CN"

[shell]
program = "nu"
args = []

[window]
width = 1420
height = 900
decorations = "Enabled"
