# æ ¹æ® schema æä¾›è‡ªåŠ¨è¡¥å…¨
"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 3000

# åœ¨æç¤ºç¬¦ä¹‹é—´æ’å…¥ç©ºè¡Œ
add_newline = true

[character]
success_symbol = '[â¯](bold red)[â¯](bold yellow)[â¯](bold green)'
error_symbol = '[â¯â¯â¯](bold red)'

[username]
show_always = true

[time]
disabled = false
format = 'ğŸ•™[\[ $time \]]($style) '

[python]
symbol = 'îœ¼ '

[git_branch]
symbol = 'ğŸŒ± '
truncation_length = 6
truncation_symbol = ''
ignore_branches = ['master', 'main']

[git_commit]
commit_hash_length = 6
tag_symbol = 'ğŸ”– '

[git_status]
conflicted = 'ğŸš©${count}'
ahead = 'ğŸƒğŸ’¨${count}'
behind = 'ğŸ˜°${count}'
diverged = 'ğŸ’£ğŸ‘†${ahead_count}ğŸ‘‡${behind_count}'
up_to_date = 'ğŸš€'
untracked = 'ğŸ¤·${count}'
stashed = 'ğŸ“¦${count}'
modified = 'ğŸ“${count}'
staged = 'ğŸ‘€${count}'
renamed = 'âœ’${count}'
deleted = 'ğŸ—‘${count}'
