[nvim.files]
nvim = "~/AppData/Local/nvim"

[lazygit.files]
lazygit = { target = "~/AppData/Roaming/lazygit/config.yml", type = "symbolic" }

[yazi.files]
yazi = { target = "~/AppData/Roaming/yazi/config", type = "symbolic" }

[nushell.files]
nushell = "~/AppData/Roaming/nushell"

[bat.files]
bat = "~/AppData/Roaming/bat"

[rio.files]
rio = "~/AppData/Local/rio"
